CREATE TABLE IF NOT EXISTS profile (
  userId VARCHAR(36) NOT NULL,
  bio VARCHAR(500) NOT NULL DEFAULT '',
  locale VARCHAR(20) NOT NULL DEFAULT '',
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (userId),
  CONSTRAINT profile_user_fk FOREIGN KEY (userId) REFERENCES `user` (id) ON DELETE CASCADE
);
